### ISSUE TITLE
Doesn't work with ScrollContainer

### ISSUE THREAD

**Issue by tavurth** [Wcubed/horizontal_flow_container#3]
Unfortunately when adding this as a child of a `ScrollContainer` node the tree is broken:

Without `ScrollContainer`
<img width="500" alt="Screenshot 2021-06-20 at 14 59 20" src="https://user-images.githubusercontent.com/100964/122673224-188d8100-d1d8-11eb-80a9-01a39f8238f1.png">

With `ScrollContainer`
<img width="500" alt="Screenshot 2021-06-20 at 14 59 36" src="https://user-images.githubusercontent.com/100964/122673236-23e0ac80-d1d8-11eb-8ac5-860f85644895.png">

**Comment by Wcubed** [comment]
Good catch. I'll look into why it is doing that.

**Comment by Wcubed** [comment]
Found the problem. The container didn't have the horizontal "FILL" flag turned on. It's now turned on by default, as it wouldn't make much sense for it to be off in in the first place :).

**Comment by tavurth** [comment]
Thank you!
